version: '3.7'

services:
  anthropic-discord-bot:
    container_name: anthropic-discord-bot
    image: ghcr.io/poma4ka/anthropic-discord-bot:latest
    restart: always
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
