name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Getting version
        run: |
          echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Getting image name from go.mod
        if: ${{ env.IMAGE_NAME == '' }}
        run: |
          echo "IMAGE_NAME=$(awk '/module/{print $2}' go.mod)" >> $GITHUB_ENV

      - name: Checking version exists
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/${{ env.VERSION }}"; then
            exit 1
          fi

      - name: Get owner
        run: |
          echo "OWNER=${repository_owner,,}" >>${GITHUB_ENV}
        env:
          repository_owner: ${{ github.repository_owner }}

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.deploy/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBody: true
